config/routes.rb
Rails.application.routes.draw do

  resources :workouts
  devise_for :users
  get 'pages/about'
  get 'pages/contact'
  get 'pages/dashboard'
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :workout_date, presence: true

  enum type: {
    run: 0,
    cycle: 1,
    swim: 2,
    strength: 3
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :current_password])
    end

    def after_sign_in_path_for(resource)
      # NOTE: resource is the current User object in this case.
      pages_dashboard_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  def home
  end

  def about
  end

  def contact
  end

  def dashboard
    @workouts = current_user.workouts
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workout, only: [:show, :edit, :update]

  def index
    @workouts = current_user.workouts
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user
    if @workout.save
      flash[:success] = "Workout was successfully created"
      redirect_to workout_path(@workout)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      flash[:success] = "Workout was updated"
      redirect_to workout_path(@workout)
    else
      render 'edit'
    end
  end

  private

    def workout_params
      params.require(:workout).permit(:title, :workout_date, :type_id, :duration_in_hr, :duration_in_min, :distance, :comment, :user_id)
    end

    def set_workout
      @workout = current_user.workouts.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger" id="error_explanation" role="alert">
      <a href='#' class='close' data-dismiss='alert' &#215;></a>
      <h3>#{sentence}</h3>
      <ul class="list-group">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">TrainerApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_about_path %>">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_contact_path %>">Contact</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav pull-right">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Workouts", workouts_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Dashboard", pages_dashboard_path, class: 'nav-link' %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
          <div class="dropdown-menu" aria-labelledby="dropdown02">
            <%= link_to "My Profile", edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>' role="alert">
          <a href="#" class="close" data-dismiss='alert'>&times;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/dashboard.html.erb
<div class="ml-3 mr-3 mt-3">
  <h1>Dashboard</h1>
  <%= link_to 'Add New Workout', new_workout_path, class: 'btn btn-primary' %>
  <hr>
  <%= image_tag "svg/bar-chart.svg", alt: "Bar Chart", class: 'icon' %>
  <h3>Graphs of progress will go here</h3>
    <%= image_tag "svg/pie-chart.svg", alt: "Bar Chart", class: 'icon' %>
  <hr>
  <h3>Workouts</h3>
  <%= render 'workouts/workouts' %>
</div>

app/views/pages/home.html.erb
<main role="main">
  <div class="jumbotron text-center" id="main-jumbotron">
    <div class="container">
      <h1 class="display-3">Progress with TrainerApp</h1>
      <p>Data is important if you want to track your progress. This app will help you build a journal to see what is working for you.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Dashboard</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Tracking</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Community</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
    <hr>
  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; TrainerApp 2018</p>
</footer>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
  <% if @workout.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
    <h2><%= pluralize(@workout.errors.count, "error") %>
    prohibited this exercise from being saved: </h2>
      <ul>
        <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :workout_date %>
        <%= f.text_field :workout_date, class: 'form-control', placeholder: 'MM-DD-YYYY', :data => {:provide => 'datepicker'} %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label 'Type' %><br>
        <%= f.select :type_id, Workout.types.keys, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label 'Duration (Hours)' %>
        <%= f.number_field :duration_in_hr, class: 'form-control', in: 0..24, placeholder: '0' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label 'Duration (Minutes)' %>
        <%= f.number_field :duration_in_min, class: 'form-control', in: 0..60, placeholder: '0' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :distance %>
        <%= f.number_field :distance, class: 'form-control', in: 0..200, step: 1, placeholder: '0.00' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', workouts_path, class: 'btn btn-warning' %>
<% end %>

app/views/workouts/_workouts.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>no</th>
        <th>Title</th>
        <th>Workout Date</th>
        <th>Type</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
      <% @workouts.each_with_index do |workout, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= workout.title %></td>
        <td><%= workout.workout_date %></td>
        <td><%= Workout.types.keys[workout.type_id].capitalize %></td>
        <td><%= link_to workout_path(workout), class: 'badge badge-success text-center' do %>
          <%= image_tag "svg/arrow-circle-right.svg", alt: "View", class: 'icon text-light' %>
        <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/workouts/edit.html.erb
<div class="container mt-3">
  <h1>Edit Workout</h1>
  <%= render 'form' %>
</div>

app/views/workouts/index.html.erb
<div class="container mt-4">
  <h1>Workouts</h1>
  <%= link_to 'Add New Workout', new_workout_path, class: 'btn btn-primary mb-3' %>
  <%= render 'workouts' %>
</div>

app/views/workouts/new.html.erb
<div class="container mt-4">
  <h1>Add Workout</h1>
  <%= render 'form' %>
</div>

app/views/workouts/show.html.erb
<div class="container mt-3">
  <div class="col-md-12">
    <div class="card bg-light">
      <div class="card-body">
        <h2 class="show-header pb-3 text-center"><%= "#{@workout.user.first_name}'s Workout Details" %></h2>
        <h4>Title: <%= @workout.title.capitalize %></h4>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <p><strong>Workout Date:</strong> <%= @workout.workout_date %></p>
          </div>
          <div class="col-md-6">
            <p><strong>Workout Type:</strong> <%= Workout.types.keys[@workout.type_id].capitalize %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h4>Duration</h4>
        <div class="row">
          <div class="col-md-4">
            <p>Hours: <%= @workout.duration_in_hr ||= '0' %></p>
          </div>
          <div class="col-md-4">
            <p>Minutes <%= @workout.duration_in_min ||= '0' %></p>
          </div>
          <div class="col-md-4">
            <p>Distance <%= @workout.distance ||= '0' %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <h4>Comment:</h4>
            <p><%= @workout.comment %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-3">
      <%= link_to 'Back', workouts_path, class: 'btn btn-info' %>
      <%= link_to 'Edit', edit_workout_path(@workout), class: 'btn btn-success' %>
    </div>
  </div>
</div>